---
apiVersion: v1
kind: Namespace
metadata:
  name: frontdoor-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontdoor
  namespace: frontdoor-ns
spec:
  selector:
    matchLabels:
      app: frontdoor
  replicas: 1
  template:
    metadata:
      labels:
        app: frontdoor
    spec:
      containers:
      - image: liamford/frontdoor:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
        name: frontdoor
        readinessProbe:
          httpGet:
            path: /api/payments/v1/actuator/health
            port: 8080
        livenessProbe:
          httpGet:
            path: /api/payments/v1/actuator/health
            port: 8080
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: frontdoor-service
  namespace: frontdoor-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: frontdoor
